### ISSUE TITLE
panic: JPGQL_DCRA - Search at depth=3 by tags

### ISSUE THREAD

**Issue by kainsk** [foliagecp/sdk#6]
// when

$ nats pub --count=100000 -s nats://nats:foliage@nats:4222 functions.graph.api.query.jpgql.dcra.root "{\"payload\":{\"query_id\":\"QUERYID\", \"jpgql_query\":\".type1.*.*[tags('t1') || tags('t4')]\"}}"

// then

```
....
time="2024-11-16T13:58:37Z" level=error msg="LLAPIQueryJPGQLDirectCacheResultAggregation evaluation timeout!"

panic: send on closed channel

goroutine 426577 [running]:
github.com/foliagecp/sdk/statefun/cache.notifySubscriber(...)
	/usr/src/app/statefun/cache/cache.go:55
github.com/foliagecp/sdk/statefun/cache.(*StoreValue).Put.func1({0x422ea6?, 0xc00e61f740?}, {0x1be5de0?, 0xc007b942a0?})
	/usr/src/app/statefun/cache/cache.go:147 +0x65
sync.(*Map).Range(0xc0113c4358, 0xc00e61f7a8)
	/usr/local/go/src/sync/map.go:476 +0x228
github.com/foliagecp/sdk/statefun/cache.(*StoreValue).Put(0xc0052cd180, {0x1bdaa20?, 0xc011bcd218}, 0x1, 0xc00e61f8c0?)
	/usr/src/app/statefun/cache/cache.go:146 +0x158
github.com/foliagecp/sdk/statefun/cache.(*Store).SetValue(0xc0001b10e0, {0xc00c9dd860, 0x54}, {0xc0184431f8, 0x2, 0x8}, 0x1, 0xffffffffffffffff, {0x0, 0x0})
	/usr/src/app/statefun/cache/cache.go:700 +0x18d
github.com/foliagecp/sdk/embedded/graph/jpgql.LLAPIQueryJPGQLDirectCacheResultAggregation.func3(0xc00e61fba0)
	/usr/src/app/embedded/graph/jpgql/jpgql.go:581 +0x226
github.com/foliagecp/sdk/embedded/graph/jpgql.LLAPIQueryJPGQLDirectCacheResultAggregation({0x1c139e0?, 0xc000257830?}, 0xc010f9f360)
	/usr/src/app/embedded/graph/jpgql/jpgql.go:628 +0xbd1
github.com/foliagecp/sdk/statefun.(*FunctionType).handleMsgForID(0xc0001fb1e0, {0xc01bd77885, 0x24}, {0xc01c30b820, 0xc010b2b680, 0xc010b2b6b0, 0xc010b2b730, 0x0, 0xc00c95cc18}, 0xc010f9f360)
	/usr/src/app/statefun/function_type.go:243 +0x66b
github.com/foliagecp/sdk/statefun.(*FunctionType).idHandlerRoutine(0xc0001fb1e0, {0xc01bd77885, 0x24}, 0xc005d2d788?)
	/usr/src/app/statefun/function_type.go:155 +0x50e
created by github.com/foliagecp/sdk/statefun.(*FunctionType).sendMsg in goroutine 4657
	/usr/src/app/statefun/function_type.go:102 +0x1b1
```

**Comment by AndreiShipov** [comment]
Thank you for issuing the problem. It will be solved it in the new release version.

**Comment by kainsk** [comment]
Проект планирует составить конкуренцию Apache Flink со Stateful Functions?

**Comment by plavrenko** [comment]
> Проект планирует составить конкуренцию Apache Flink Stateful Functions?
> 
> eq https://nightlies.apache.org/flink/flink-statefun-docs-stable

Foliage does not aim to compete directly with Apache Flink, as it is designed to address different challenges. While it takes inspiration from Apache Flink (Stateful Functions) and implements some similar features, its primary focus is on distributed and asynchronous computations over large graph structures. Specifically, it targets graph-based digital twins of real-world systems for analysis and control.

Initially, we started with Apache Flink, but eventually moved away from it. Our implementation offers several advantages:
1. Performance: Our solution is faster.
2. Local Caching: Unlike Flink, we incorporate a local cache for enhanced efficiency.
3. Context-Aware Functions: Foliage functions operate not only within their own context but also in the context of the graph model’s objects. This graph model is an integral part of our platform and sets it apart from Flink.
